//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ColoresEntities2 : DbContext
    {
        public ColoresEntities2()
            : base("name=ColoresEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoriaproducto> Categoriaproducto { get; set; }
        public virtual DbSet<Detallepago> Detallepago { get; set; }
        public virtual DbSet<Hojadetalle> Hojadetalle { get; set; }
        public virtual DbSet<Hojaencabezado> Hojaencabezado { get; set; }
        public virtual DbSet<Pago> Pago { get; set; }
        public virtual DbSet<Permiso> Permiso { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Tipopago> Tipopago { get; set; }
        public virtual DbSet<Tipoproducto> Tipoproducto { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
