//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detallepago
    {
        public int DetallepagoId { get; set; }
        public Nullable<int> HojaencabezadoId { get; set; }
        public Nullable<int> PagoId { get; set; }
    
        public virtual Hojaencabezado Hojaencabezado { get; set; }
        public virtual Pago Pago { get; set; }
    }
}
