//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hojaencabezado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hojaencabezado()
        {
            this.Detallepago = new HashSet<Detallepago>();
            this.Hojadetalle = new HashSet<Hojadetalle>();
        }
    
        public int HojaencabezadoId { get; set; }
        public string Serie { get; set; }
        public System.DateTime Fechacreacion { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public double Total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detallepago> Detallepago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hojadetalle> Hojadetalle { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
