//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pago()
        {
            this.Detallepago = new HashSet<Detallepago>();
        }
    
        public int PagoId { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public int CodigoTarjeta { get; set; }
        public Nullable<System.DateTime> Fechaexpedido { get; set; }
        public Nullable<System.DateTime> Fechaacreditacion { get; set; }
        public string Nocheque { get; set; }
        public string Nocuenta { get; set; }
        public double Cantidad { get; set; }
        public string Notarjeta { get; set; }
        public string Caducidad { get; set; }
        public Nullable<int> TipopagoId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detallepago> Detallepago { get; set; }
        public virtual Tipopago Tipopago { get; set; }
    }
}
