//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Hojadetalle = new HashSet<Hojadetalle>();
        }
    
        public int ProductoId { get; set; }
        public string Nombre { get; set; }
        public double Precioventa { get; set; }
        public double Preciocompra { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<double> Descuento { get; set; }
        public string Descripcion { get; set; }
        public int Existencia { get; set; }
        public string Duracion { get; set; }
        public string Extension { get; set; }
        public string Color { get; set; }
        public Nullable<int> TipoproductoId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hojadetalle> Hojadetalle { get; set; }
        public virtual Tipoproducto Tipoproducto { get; set; }
    }
}
